#!/bin/sh
#
# 2013 James Howlett
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#

destination="/etc/snmp/snmpd.conf"
os="$(cat "$__global/explorer/os")"
require=""

case "$os" in
  centos|redhat)
    source="$__type/files/centos"
    __package net-snmp --state present
    require="__package/net-snmp"
  ;;
  debian|ubuntu)
    source="$__type/files/debian"
    __package snmpd --state present
    require="__package/snmpd"
    require=$require __key_value SNMPDOPTS --file /etc/default/snmpd --delimiter '=' --value "'-LS6d -Lf /dev/null -u snmp -g snmp -I -smux -p /var/run/snmpd.pid'"
    require=$require __key_value TRAPDOPTS --file /etc/default/snmpd --delimiter '=' --value "'-LS6d -p /var/run/snmptrapd.pid'"

  ;;
  *)
    source=""
  ;;
esac

if [ -n "$source" ] ; then
  require=$require __file "$destination" --source "$source"
fi

