#!/bin/sh
#
# 2013 James Howlett
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#

#destination=/etc/issue
#
#os="$(cat "$__global/explorer/os")"
#
#if [ -f "$__object/parameter/source" ]; then
#    source="$(cat "$__object/parameter/source")"
#else
#    case "$os" in
#        archlinux|redhat)
#            source="$__type/files/$os"
#        ;;
#        *)
#            source="$__type/files/default"
#        ;;
#    esac
#fi
#
#__file "$destination" --source "$source"

# Note: Order code is run is manifest, gencode-local, gencode-remote

dir="/root/cdist/zerodisk"
__directory "$dir" --parents --state present
export require="__directory/$dir"
__file /root/cdist/zerodisk/Makefile --source "$__type/files/Makefile" --state present
__file /root/cdist/zerodisk/zerodisk.c --source "$__type/files/zerodisk.c" --state present

__line rc.local1 --file /etc/rc.local --line 'exit 0' --state absent
__line rc.local2 --file /etc/rc.local --line "/usr/sbin/zerodisk -f /zerodisk --min 8 --max 10 --freq 30 --rate 1024" --state present

