#!/bin/sh
#
# 2013 James Howlett
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#

os="$(cat "$__global/explorer/os")"
require=""

case "$os" in
  debian|ubuntu)
      for i in open-iscsi iscsitarget iscsitarget-dkms multipath-tools; do
        __package $i --state present
        require="$require __package/$i"
      done
      require=$require __file "/etc/iscsi/iscsid.conf" --source "$__type/files/debian-iscsid.conf" --mode 0644
      require=$require __file "/etc/multipath.conf" --source "$__type/files/debian-multipath.conf" --mode 0644
  ;;
  *)
    echo "WARNING: $os not supported yet for iscsi configuration"
  ;;
esac


